// The DishTap dish pool — famous dishes with the place they're most strongly
// rooted in. Scoring is country-first: a tap anywhere in `country` is a
// bullseye; otherwise the city/region coordinates drive distance-based partial
// credit. Contested origins get the historically-strongest claim, with the
// debate in the fact line.

export type Dish = {
  id: string;
  name: string;
  emoji: string;
  /** Display name of the origin, e.g. "Naples, Italy" */
  place: string;
  /**
   * Origin country for tap scoring — must exactly match a `properties.name`
   * in $lib/data/world-countries-110m.json (exception: Singapore, absent from
   * the 110m dataset, so laksa scores purely by distance).
   */
  country: string;
  lat: number;
  lon: number;
  /** One kid-friendly sentence shown on the reveal card. */
  fact: string;
};

export const DISHES: Dish[] = [
  {
    id: "pizza",
    name: "Pizza Margherita",
    emoji: "🍕",
    place: "Naples, Italy",
    country: "Italy",
    lat: 40.85,
    lon: 14.27,
    fact: "Legend says it was made in 1889 for Queen Margherita, with tomato, mozzarella, and basil to match the Italian flag.",
  },
  {
    id: "sushi",
    name: "Sushi",
    emoji: "🍣",
    place: "Tokyo, Japan",
    country: "Japan",
    lat: 35.68,
    lon: 139.69,
    fact: "Modern nigiri sushi began as fast street food in 1800s Edo — the old name for Tokyo.",
  },
  {
    id: "tacos",
    name: "Tacos al Pastor",
    emoji: "🌮",
    place: "Mexico City, Mexico",
    country: "Mexico",
    lat: 19.43,
    lon: -99.13,
    fact: "It was born when Lebanese immigrants brought spit-roasted meat to Mexico and locals swapped in pork and pineapple.",
  },
  {
    id: "croissant",
    name: "Croissant",
    emoji: "🥐",
    place: "Paris, France",
    country: "France",
    lat: 48.86,
    lon: 2.35,
    fact: "Paris made it famous, but its crescent-shaped ancestor, the kipferl, actually came from Vienna.",
  },
  {
    id: "pad-thai",
    name: "Pad Thai",
    emoji: "🍜",
    place: "Bangkok, Thailand",
    country: "Thailand",
    lat: 13.76,
    lon: 100.5,
    fact: "Thailand's government promoted it in the 1930s as a national dish — there was even a recipe poster campaign.",
  },
  {
    id: "paella",
    name: "Paella",
    emoji: "🥘",
    place: "Valencia, Spain",
    country: "Spain",
    lat: 39.47,
    lon: -0.38,
    fact: "Farmers near Valencia's rice fields cooked it over orange-wood fires; 'paella' is the name of the wide pan.",
  },
  {
    id: "poutine",
    name: "Poutine",
    emoji: "🍟",
    place: "Quebec, Canada",
    country: "Canada",
    lat: 46.81,
    lon: -71.21,
    fact: "Fries, cheese curds, and gravy — invented in rural Quebec in the 1950s, where fresh curds famously squeak.",
  },
  {
    id: "pierogi",
    name: "Pierogi",
    emoji: "🥟",
    place: "Kraków, Poland",
    country: "Poland",
    lat: 50.06,
    lon: 19.94,
    fact: "Poland loves these stuffed dumplings so much there's an annual pierogi festival in Kraków every August.",
  },
  {
    id: "baklava",
    name: "Baklava",
    emoji: "🍯",
    place: "Istanbul, Türkiye",
    country: "Turkey",
    lat: 41.01,
    lon: 28.98,
    fact: "Paper-thin pastry layered with nuts and honey was perfected in the Ottoman palace kitchens of Istanbul.",
  },
  {
    id: "kimchi",
    name: "Kimchi",
    emoji: "🥬",
    place: "Seoul, South Korea",
    country: "South Korea",
    lat: 37.57,
    lon: 126.98,
    fact: "Koreans have fermented spicy cabbage for over a thousand years — many families still make a giant winter batch together.",
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    emoji: "🍛",
    place: "Delhi, India",
    country: "India",
    lat: 28.61,
    lon: 77.21,
    fact: "A Delhi restaurant invented it in the 1950s to rescue leftover tandoori chicken with a creamy tomato sauce.",
  },
  {
    id: "peking-duck",
    name: "Peking Duck",
    emoji: "🦆",
    place: "Beijing, China",
    country: "China",
    lat: 39.9,
    lon: 116.4,
    fact: "It was served in Beijing's imperial court for centuries — the crispy skin is the most prized part.",
  },
  {
    id: "pho",
    name: "Pho",
    emoji: "🍲",
    place: "Hanoi, Vietnam",
    country: "Vietnam",
    lat: 21.03,
    lon: 105.85,
    fact: "This fragrant noodle soup started as a breakfast sold by street vendors in early-1900s Hanoi.",
  },
  {
    id: "ceviche",
    name: "Ceviche",
    emoji: "🐟",
    place: "Lima, Peru",
    country: "Peru",
    lat: -12.05,
    lon: -77.04,
    fact: "Fresh fish 'cooked' in citrus juice — Peru loves it so much it has a national Ceviche Day.",
  },
  {
    id: "feijoada",
    name: "Feijoada",
    emoji: "🫘",
    place: "Rio de Janeiro, Brazil",
    country: "Brazil",
    lat: -22.91,
    lon: -43.17,
    fact: "Brazil's beloved black-bean stew is a weekend ritual, traditionally eaten slowly over a long lunch.",
  },
  {
    id: "asado",
    name: "Asado",
    emoji: "🥩",
    place: "Buenos Aires, Argentina",
    country: "Argentina",
    lat: -34.6,
    lon: -58.38,
    fact: "Argentina's slow barbecue tradition comes from the gauchos — cowboys who grilled over open embers on the pampas.",
  },
  {
    id: "jollof",
    name: "Jollof Rice",
    emoji: "🍚",
    place: "Saint-Louis, Senegal",
    country: "Senegal",
    lat: 16.03,
    lon: -16.49,
    fact: "It traces back to the Wolof people of Senegal — though Ghana and Nigeria still argue over who makes it best.",
  },
  {
    id: "tagine",
    name: "Tagine",
    emoji: "🍢",
    place: "Marrakesh, Morocco",
    country: "Morocco",
    lat: 31.63,
    lon: -7.99,
    fact: "Named after its cone-lidded clay pot, which traps steam so the stew cooks with barely any water — handy at the desert's edge.",
  },
  {
    id: "koshari",
    name: "Koshari",
    emoji: "🍝",
    place: "Cairo, Egypt",
    country: "Egypt",
    lat: 30.04,
    lon: 31.24,
    fact: "Egypt's favorite street food piles rice, lentils, pasta, and crispy onions into one glorious bowl.",
  },
  {
    id: "injera",
    name: "Injera",
    emoji: "🫓",
    place: "Addis Ababa, Ethiopia",
    country: "Ethiopia",
    lat: 9.01,
    lon: 38.75,
    fact: "This spongy sourdough flatbread is plate, fork, and food in one — you tear it to scoop up stews.",
  },
  {
    id: "bunny-chow",
    name: "Bunny Chow",
    emoji: "🍞",
    place: "Durban, South Africa",
    country: "South Africa",
    lat: -29.86,
    lon: 31.03,
    fact: "No bunnies involved — it's curry served inside a hollowed-out loaf of bread, invented in Durban.",
  },
  {
    id: "fish-and-chips",
    name: "Fish and Chips",
    emoji: "🐠",
    place: "London, England",
    country: "United Kingdom",
    lat: 51.51,
    lon: -0.13,
    fact: "Britain loved it so much that during World War II it was one of the few foods never rationed.",
  },
  {
    id: "haggis",
    name: "Haggis",
    emoji: "🥔",
    place: "Edinburgh, Scotland",
    country: "United Kingdom",
    lat: 55.95,
    lon: -3.19,
    fact: "Scotland's national dish gets its own holiday — on Burns Night it's carried in while bagpipes play.",
  },
  {
    id: "tikka-masala",
    name: "Chicken Tikka Masala",
    emoji: "🍅",
    place: "Glasgow, Scotland",
    country: "United Kingdom",
    lat: 55.86,
    lon: -4.25,
    fact: "Surprise! The story goes that a chef in Glasgow invented it when a customer wanted sauce on his tandoori chicken.",
  },
  {
    id: "irish-stew",
    name: "Irish Stew",
    emoji: "🥣",
    place: "Dublin, Ireland",
    country: "Ireland",
    lat: 53.35,
    lon: -6.26,
    fact: "Ireland's slow-simmered lamb and potato stew has been warming people up since the 1700s.",
  },
  {
    id: "meatballs",
    name: "Swedish Meatballs",
    emoji: "🧆",
    place: "Stockholm, Sweden",
    country: "Sweden",
    lat: 59.33,
    lon: 18.07,
    fact: "In 2018 Sweden's official account admitted the recipe likely came home with a king who visited Türkiye.",
  },
  {
    id: "smorrebrod",
    name: "Smørrebrød",
    emoji: "🥪",
    place: "Copenhagen, Denmark",
    country: "Denmark",
    lat: 55.68,
    lon: 12.57,
    fact: "Denmark's open-faced sandwich is eaten with a knife and fork — never with your hands.",
  },
  {
    id: "fondue",
    name: "Cheese Fondue",
    emoji: "🧀",
    place: "The Alps, Switzerland",
    country: "Switzerland",
    lat: 46.8,
    lon: 8.23,
    fact: "Swiss mountain villagers melted their hard winter cheese to make it easier to eat — and dipping bread became a national sport.",
  },
  {
    id: "schnitzel",
    name: "Wiener Schnitzel",
    emoji: "🍖",
    place: "Vienna, Austria",
    country: "Austria",
    lat: 48.21,
    lon: 16.37,
    fact: "'Wiener' means 'from Vienna' — by law in Austria, a true one must be made of veal.",
  },
  {
    id: "pretzel",
    name: "Pretzel",
    emoji: "🥨",
    place: "Munich, Germany",
    country: "Germany",
    lat: 48.14,
    lon: 11.58,
    fact: "Legend credits monks who twisted dough to look like arms folded in prayer; Bavaria made it an icon.",
  },
  {
    id: "stroopwafel",
    name: "Stroopwafel",
    emoji: "🧇",
    place: "Gouda, Netherlands",
    country: "Netherlands",
    lat: 52.01,
    lon: 4.71,
    fact: "Invented in Gouda — the trick is resting it on top of a hot drink so the caramel middle goes gooey.",
  },
  {
    id: "waffles",
    name: "Belgian Waffles",
    emoji: "🧇",
    place: "Brussels, Belgium",
    country: "Belgium",
    lat: 50.85,
    lon: 4.35,
    fact: "Belgium has two rival waffles — the light rectangular Brussels and the chewy caramelized Liège.",
  },
  {
    id: "moussaka",
    name: "Moussaka",
    emoji: "🍆",
    place: "Athens, Greece",
    country: "Greece",
    lat: 37.98,
    lon: 23.73,
    fact: "The layered eggplant bake got its famous creamy top in the 1920s from Greek chef Nikolaos Tselementes.",
  },
  {
    id: "borscht",
    name: "Borscht",
    emoji: "🍜",
    place: "Kyiv, Ukraine",
    country: "Ukraine",
    lat: 50.45,
    lon: 30.52,
    fact: "Ukraine's beet soup is so treasured that UNESCO added its cooking culture to the world heritage list.",
  },
  {
    id: "goulash",
    name: "Goulash",
    emoji: "🐂",
    place: "Budapest, Hungary",
    country: "Hungary",
    lat: 47.5,
    lon: 19.04,
    fact: "It began as a herdsman's kettle stew on the Hungarian plains — 'gulyás' literally means cowboy.",
  },
  {
    id: "pastel-de-nata",
    name: "Pastel de Nata",
    emoji: "🥧",
    place: "Lisbon, Portugal",
    country: "Portugal",
    lat: 38.72,
    lon: -9.14,
    fact: "Monks in Lisbon invented these custard tarts, and the original 1837 bakery still keeps its recipe secret.",
  },
  {
    id: "skyr",
    name: "Skyr",
    emoji: "🥛",
    place: "Reykjavík, Iceland",
    country: "Iceland",
    lat: 64.15,
    lon: -21.94,
    fact: "Vikings brought this thick, creamy dairy to Iceland over 1,000 years ago — it's technically a soft cheese.",
  },
  {
    id: "shakshuka",
    name: "Shakshuka",
    emoji: "🍳",
    place: "Tunis, Tunisia",
    country: "Tunisia",
    lat: 36.81,
    lon: 10.18,
    fact: "Eggs poached in spiced tomato sauce — the name comes from North African Arabic for 'all mixed up.'",
  },
  {
    id: "nyama-choma",
    name: "Nyama Choma",
    emoji: "🍖",
    place: "Nairobi, Kenya",
    country: "Kenya",
    lat: -1.29,
    lon: 36.82,
    fact: "Kenya's favorite grilled meat is a social event — it's shared straight off the cutting board with friends.",
  },
  {
    id: "piri-piri",
    name: "Piri-Piri Chicken",
    emoji: "🌶️",
    place: "Maputo, Mozambique",
    country: "Mozambique",
    lat: -25.97,
    lon: 32.57,
    fact: "It was born where Portuguese sailors met Mozambique's fiery bird's-eye chili — 'piri-piri' means pepper-pepper.",
  },
  {
    id: "fufu",
    name: "Fufu",
    emoji: "🍠",
    place: "Accra, Ghana",
    country: "Ghana",
    lat: 5.6,
    lon: -0.19,
    fact: "Pounded cassava and plantain, stretched like dough — you pinch off a piece and scoop soup with it.",
  },
  {
    id: "poke",
    name: "Poke",
    emoji: "🐡",
    place: "Honolulu, Hawaii",
    country: "United States of America",
    lat: 21.31,
    lon: -157.86,
    fact: "Hawaiian fishers seasoned fresh-caught fish right on the boat — 'poke' means 'to slice' in Hawaiian.",
  },
  {
    id: "texas-bbq",
    name: "Texas BBQ Brisket",
    emoji: "🤠",
    place: "Austin, Texas, USA",
    country: "United States of America",
    lat: 30.27,
    lon: -97.74,
    fact: "Central Texas pitmasters smoke brisket for up to 18 hours — the best joints sell out by lunchtime.",
  },
  {
    id: "key-lime-pie",
    name: "Key Lime Pie",
    emoji: "🥧",
    place: "Key West, Florida, USA",
    country: "United States of America",
    lat: 24.56,
    lon: -81.78,
    fact: "It's named for the tiny, extra-tart limes that grow in the Florida Keys — and it's Florida's official state pie.",
  },
  {
    id: "jerk-chicken",
    name: "Jerk Chicken",
    emoji: "🔥",
    place: "Kingston, Jamaica",
    country: "Jamaica",
    lat: 17.97,
    lon: -76.79,
    fact: "The smoky-spicy 'jerk' technique was created by Jamaica's Maroons, who cooked over pimento wood.",
  },
  {
    id: "mole",
    name: "Mole Poblano",
    emoji: "🍫",
    place: "Puebla, Mexico",
    country: "Mexico",
    lat: 19.04,
    lon: -98.2,
    fact: "This rich sauce can have more than 20 ingredients — including chocolate and chiles together.",
  },
  {
    id: "ropa-vieja",
    name: "Ropa Vieja",
    emoji: "🥘",
    place: "Havana, Cuba",
    country: "Cuba",
    lat: 23.11,
    lon: -82.37,
    fact: "The name means 'old clothes' — the shredded beef is supposed to look like torn-up rags. Yum?",
  },
  {
    id: "pupusa",
    name: "Pupusas",
    emoji: "🫓",
    place: "San Salvador, El Salvador",
    country: "El Salvador",
    lat: 13.69,
    lon: -89.22,
    fact: "El Salvador's stuffed corn cakes are so beloved there's a national Pupusa Day every November.",
  },
  {
    id: "arepa",
    name: "Arepas",
    emoji: "🌽",
    place: "Caracas, Venezuela",
    country: "Venezuela",
    lat: 10.48,
    lon: -66.9,
    fact: "These grilled corn pockets have been made for thousands of years — Venezuela and Colombia both call them their own.",
  },
  {
    id: "empanada",
    name: "Empanadas",
    emoji: "🥟",
    place: "Salta, Argentina",
    country: "Argentina",
    lat: -24.79,
    lon: -65.41,
    fact: "The idea sailed over from Galicia in Spain, but Argentina's provinces each bake their own proud version.",
  },
  {
    id: "gelato",
    name: "Gelato",
    emoji: "🍨",
    place: "Florence, Italy",
    country: "Italy",
    lat: 43.77,
    lon: 11.26,
    fact: "Renaissance Florence gets the credit — an architect named Buontalenti wowed the Medici court with it.",
  },
  {
    id: "crepes",
    name: "Crêpes",
    emoji: "🥞",
    place: "Brittany, France",
    country: "France",
    lat: 48.11,
    lon: -1.68,
    fact: "They come from Brittany, where buckwheat crêpes are savory and there's even a holiday for flipping them.",
  },
  {
    id: "churros",
    name: "Churros",
    emoji: "🍩",
    place: "Madrid, Spain",
    country: "Spain",
    lat: 40.42,
    lon: -3.7,
    fact: "In Madrid the classic move is dunking them in thick hot chocolate — sometimes for breakfast.",
  },
  {
    id: "ramen",
    name: "Tonkotsu Ramen",
    emoji: "🍥",
    place: "Fukuoka, Japan",
    country: "Japan",
    lat: 33.59,
    lon: 130.4,
    fact: "Fukuoka's creamy pork-bone ramen simmers for many hours — the city has entire streets of ramen stalls.",
  },
  {
    id: "dim-sum",
    name: "Dim Sum",
    emoji: "🥢",
    place: "Guangzhou, China",
    country: "China",
    lat: 23.13,
    lon: 113.26,
    fact: "It grew out of Guangzhou's tea houses, where travelers snacked on little baskets of dumplings with their tea.",
  },
  {
    id: "laksa",
    name: "Laksa",
    emoji: "🦐",
    place: "Singapore",
    country: "Singapore",
    lat: 1.35,
    lon: 103.82,
    fact: "This spicy coconut noodle soup was born where Chinese and Malay cooking met along the old trade routes.",
  },
  {
    id: "nasi-goreng",
    name: "Nasi Goreng",
    emoji: "🍛",
    place: "Jakarta, Indonesia",
    country: "Indonesia",
    lat: -6.21,
    lon: 106.85,
    fact: "Indonesia's 'fried rice' is a genius way to use yesterday's rice — many eat it for breakfast with a fried egg on top.",
  },
  {
    id: "adobo",
    name: "Chicken Adobo",
    emoji: "🍗",
    place: "Manila, Philippines",
    country: "Philippines",
    lat: 14.6,
    lon: 120.98,
    fact: "Filipinos were braising meat in vinegar and soy long before the Spanish arrived and gave it the name adobo.",
  },
  {
    id: "momo",
    name: "Momos",
    emoji: "🏔️",
    place: "Kathmandu, Nepal",
    country: "Nepal",
    lat: 27.72,
    lon: 85.32,
    fact: "These Himalayan dumplings traveled the mountain passes with Tibetan and Newari traders — now they're Nepal's favorite snack.",
  },
  {
    id: "biryani",
    name: "Biryani",
    emoji: "🍚",
    place: "Hyderabad, India",
    country: "India",
    lat: 17.39,
    lon: 78.49,
    fact: "Hyderabad's famous version cooks the rice and meat together sealed under a dough lid so no steam escapes.",
  },
  {
    id: "xiaolongbao",
    name: "Xiaolongbao",
    emoji: "🥟",
    place: "Shanghai, China",
    country: "China",
    lat: 31.23,
    lon: 121.47,
    fact: "These 'soup dumplings' hide hot broth inside — the secret is jellied stock that melts as they steam.",
  },
  {
    id: "plov",
    name: "Plov",
    emoji: "🥕",
    place: "Tashkent, Uzbekistan",
    country: "Uzbekistan",
    lat: 41.3,
    lon: 69.24,
    fact: "Uzbekistan's rice feast is cooked by masters in giant pots called kazans — one pot can feed hundreds.",
  },
  {
    id: "khachapuri",
    name: "Khachapuri",
    emoji: "⛵",
    place: "Tbilisi, Georgia",
    country: "Georgia",
    lat: 41.72,
    lon: 44.79,
    fact: "Georgia's cheese bread comes boat-shaped with an egg on top — you stir it all together and tear off the crust to dip.",
  },
  {
    id: "tahdig",
    name: "Tahdig",
    emoji: "🍚",
    place: "Tehran, Iran",
    country: "Iran",
    lat: 35.69,
    lon: 51.39,
    fact: "Persian cooks compete over this golden crispy rice from the bottom of the pot — the name means 'bottom of the pot.'",
  },
  {
    id: "kabsa",
    name: "Kabsa",
    emoji: "🍗",
    place: "Riyadh, Saudi Arabia",
    country: "Saudi Arabia",
    lat: 24.71,
    lon: 46.68,
    fact: "Saudi Arabia's spiced rice platter is made for sharing — everyone gathers around one big dish.",
  },
  {
    id: "mansaf",
    name: "Mansaf",
    emoji: "🐑",
    place: "Amman, Jordan",
    country: "Jordan",
    lat: 31.95,
    lon: 35.93,
    fact: "Jordan's national dish uses a tangy dried-yogurt sauce called jameed, and it's traditionally eaten with the right hand.",
  },
  {
    id: "pelmeni",
    name: "Pelmeni",
    emoji: "❄️",
    place: "Ural Mountains, Russia",
    country: "Russia",
    lat: 56.84,
    lon: 60.61,
    fact: "Siberian families made these little dumplings by the hundreds and froze them outside in the snow.",
  },
  {
    id: "banh-mi",
    name: "Bánh Mì",
    emoji: "🥖",
    place: "Ho Chi Minh City, Vietnam",
    country: "Vietnam",
    lat: 10.82,
    lon: 106.63,
    fact: "It mixes a French baguette with Vietnamese fillings — a mashup from when France occupied Vietnam.",
  },
  {
    id: "char-kway-teow",
    name: "Char Kway Teow",
    emoji: "🍤",
    place: "Penang, Malaysia",
    country: "Malaysia",
    lat: 5.42,
    lon: 100.33,
    fact: "Penang's smoky fried noodles get their flavor from 'wok hei' — the breath of a blazing-hot wok.",
  },
  {
    id: "pavlova",
    name: "Pavlova",
    emoji: "🍓",
    place: "Wellington, New Zealand",
    country: "New Zealand",
    lat: -41.29,
    lon: 174.78,
    fact: "Named for a visiting ballerina — New Zealand and Australia have argued for a century over who invented it.",
  },
  {
    id: "meat-pie",
    name: "Meat Pie",
    emoji: "🥧",
    place: "Sydney, Australia",
    country: "Australia",
    lat: -33.87,
    lon: 151.21,
    fact: "Australians eat about 270 million of these hand-sized pies a year — it's the classic footy-stadium snack.",
  },
  {
    id: "lamington",
    name: "Lamingtons",
    emoji: "🍰",
    place: "Brisbane, Australia",
    country: "Australia",
    lat: -27.47,
    lon: 153.03,
    fact: "Sponge cake dipped in chocolate and coconut, supposedly named after a Queensland governor, Lord Lamington.",
  },
  {
    id: "kokoda",
    name: "Kokoda",
    emoji: "🥥",
    place: "Suva, Fiji",
    country: "Fiji",
    lat: -18.14,
    lon: 178.44,
    fact: "Fiji's answer to ceviche — fresh fish cured in lime and served swimming in coconut cream.",
  },
];
