// The DishTap dish pool — famous dishes with the place they're most strongly
// rooted in. Scoring is country-first: a tap anywhere in `country` is a
// bullseye; otherwise the city/region coordinates drive distance-based partial
// credit. Contested origins get the historically-strongest claim, with the
// debate in the fact line.

export type Dish = {
  id: string;
  name: string;
  emoji?: string;
  /** Display name of the origin, e.g. "Naples, Italy" */
  place: string;
  /**
   * Origin country for tap scoring — must exactly match a `properties.name`
   * in $lib/data/world-countries-110m.json (exception: Singapore, absent from
   * the 110m dataset, so laksa scores purely by distance).
   */
  country: string;
  lat: number;
  lon: number;
  /** One kid-friendly sentence shown on the reveal card. */
  fact: string;
};

export const DISHES: Dish[] = [
  {
    id: "pizza",
    name: "Pizza Margherita",
    emoji: "🍕",
    place: "Naples, Italy",
    country: "Italy",
    lat: 40.85,
    lon: 14.27,
    fact: "Legend says it was made in 1889 for Queen Margherita, with tomato, mozzarella, and basil to match the Italian flag.",
  },
  {
    id: "sushi",
    name: "Sushi",
    emoji: "🍣",
    place: "Tokyo, Japan",
    country: "Japan",
    lat: 35.68,
    lon: 139.69,
    fact: "Modern nigiri sushi began as fast street food in 1800s Edo — the old name for Tokyo.",
  },
  {
    id: "tacos",
    name: "Tacos al Pastor",
    emoji: "🌮",
    place: "Mexico City, Mexico",
    country: "Mexico",
    lat: 19.43,
    lon: -99.13,
    fact: "It was born when Lebanese immigrants brought spit-roasted meat to Mexico and locals swapped in pork and pineapple.",
  },
  {
    id: "croissant",
    name: "Croissant",
    emoji: "🥐",
    place: "Paris, France",
    country: "France",
    lat: 48.86,
    lon: 2.35,
    fact: "Paris made it famous, but its crescent-shaped ancestor, the kipferl, actually came from Vienna.",
  },
  {
    id: "pad-thai",
    name: "Pad Thai",
    emoji: "🍜",
    place: "Bangkok, Thailand",
    country: "Thailand",
    lat: 13.76,
    lon: 100.5,
    fact: "Thailand's government promoted it in the 1930s as a national dish — there was even a recipe poster campaign.",
  },
  {
    id: "paella",
    name: "Paella",
    emoji: "🥘",
    place: "Valencia, Spain",
    country: "Spain",
    lat: 39.47,
    lon: -0.38,
    fact: "Farmers near Valencia's rice fields cooked it over orange-wood fires; 'paella' is the name of the wide pan.",
  },
  {
    id: "poutine",
    name: "Poutine",
    emoji: "🍟",
    place: "Quebec, Canada",
    country: "Canada",
    lat: 46.81,
    lon: -71.21,
    fact: "Fries, cheese curds, and gravy — invented in rural Quebec in the 1950s, where fresh curds famously squeak.",
  },
  {
    id: "pierogi",
    name: "Pierogi",
    emoji: "🥟",
    place: "Kraków, Poland",
    country: "Poland",
    lat: 50.06,
    lon: 19.94,
    fact: "Poland loves these stuffed dumplings so much there's an annual pierogi festival in Kraków every August.",
  },
  {
    id: "baklava",
    name: "Baklava",
    emoji: "🍯",
    place: "Istanbul, Türkiye",
    country: "Turkey",
    lat: 41.01,
    lon: 28.98,
    fact: "Paper-thin pastry layered with nuts and honey was perfected in the Ottoman palace kitchens of Istanbul.",
  },
  {
    id: "kimchi",
    name: "Kimchi",
    emoji: "🥬",
    place: "Seoul, South Korea",
    country: "South Korea",
    lat: 37.57,
    lon: 126.98,
    fact: "Koreans have fermented spicy cabbage for over a thousand years — many families still make a giant winter batch together.",
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    emoji: "🍛",
    place: "Delhi, India",
    country: "India",
    lat: 28.61,
    lon: 77.21,
    fact: "A Delhi restaurant invented it in the 1950s to rescue leftover tandoori chicken with a creamy tomato sauce.",
  },
  {
    id: "peking-duck",
    name: "Peking Duck",
    emoji: "🦆",
    place: "Beijing, China",
    country: "China",
    lat: 39.9,
    lon: 116.4,
    fact: "It was served in Beijing's imperial court for centuries — the crispy skin is the most prized part.",
  },
  {
    id: "pho",
    name: "Pho",
    emoji: "🍲",
    place: "Hanoi, Vietnam",
    country: "Vietnam",
    lat: 21.03,
    lon: 105.85,
    fact: "This fragrant noodle soup started as a breakfast sold by street vendors in early-1900s Hanoi.",
  },
  {
    id: "ceviche",
    name: "Ceviche",
    emoji: "🐟",
    place: "Lima, Peru",
    country: "Peru",
    lat: -12.05,
    lon: -77.04,
    fact: "Fresh fish 'cooked' in citrus juice — Peru loves it so much it has a national Ceviche Day.",
  },
  {
    id: "feijoada",
    name: "Feijoada",
    emoji: "🫘",
    place: "Rio de Janeiro, Brazil",
    country: "Brazil",
    lat: -22.91,
    lon: -43.17,
    fact: "Brazil's beloved black-bean stew is a weekend ritual, traditionally eaten slowly over a long lunch.",
  },
  {
    id: "asado",
    name: "Asado",
    emoji: "🥩",
    place: "Buenos Aires, Argentina",
    country: "Argentina",
    lat: -34.6,
    lon: -58.38,
    fact: "Argentina's slow barbecue tradition comes from the gauchos — cowboys who grilled over open embers on the pampas.",
  },
  {
    id: "jollof",
    name: "Jollof Rice",
    emoji: "🍚",
    place: "Saint-Louis, Senegal",
    country: "Senegal",
    lat: 16.03,
    lon: -16.49,
    fact: "It traces back to the Wolof people of Senegal — though Ghana and Nigeria still argue over who makes it best.",
  },
  {
    id: "tagine",
    name: "Tagine",
    emoji: "🍢",
    place: "Marrakesh, Morocco",
    country: "Morocco",
    lat: 31.63,
    lon: -7.99,
    fact: "Named after its cone-lidded clay pot, which traps steam so the stew cooks with barely any water — handy at the desert's edge.",
  },
  {
    id: "koshari",
    name: "Koshari",
    emoji: "🍝",
    place: "Cairo, Egypt",
    country: "Egypt",
    lat: 30.04,
    lon: 31.24,
    fact: "Egypt's favorite street food piles rice, lentils, pasta, and crispy onions into one glorious bowl.",
  },
  {
    id: "injera",
    name: "Injera",
    emoji: "🫓",
    place: "Addis Ababa, Ethiopia",
    country: "Ethiopia",
    lat: 9.01,
    lon: 38.75,
    fact: "This spongy sourdough flatbread is plate, fork, and food in one — you tear it to scoop up stews.",
  },
  {
    id: "bunny-chow",
    name: "Bunny Chow",
    emoji: "🍞",
    place: "Durban, South Africa",
    country: "South Africa",
    lat: -29.86,
    lon: 31.03,
    fact: "No bunnies involved — it's curry served inside a hollowed-out loaf of bread, invented in Durban.",
  },
  {
    id: "fish-and-chips",
    name: "Fish and Chips",
    emoji: "🐠",
    place: "London, England",
    country: "United Kingdom",
    lat: 51.51,
    lon: -0.13,
    fact: "Britain loved it so much that during World War II it was one of the few foods never rationed.",
  },
  {
    id: "haggis",
    name: "Haggis",
    emoji: "🥔",
    place: "Edinburgh, Scotland",
    country: "United Kingdom",
    lat: 55.95,
    lon: -3.19,
    fact: "Scotland's national dish gets its own holiday — on Burns Night it's carried in while bagpipes play.",
  },
  {
    id: "tikka-masala",
    name: "Chicken Tikka Masala",
    emoji: "🍅",
    place: "Glasgow, Scotland",
    country: "United Kingdom",
    lat: 55.86,
    lon: -4.25,
    fact: "Surprise! The story goes that a chef in Glasgow invented it when a customer wanted sauce on his tandoori chicken.",
  },
  {
    id: "irish-stew",
    name: "Irish Stew",
    emoji: "🥣",
    place: "Dublin, Ireland",
    country: "Ireland",
    lat: 53.35,
    lon: -6.26,
    fact: "Ireland's slow-simmered lamb and potato stew has been warming people up since the 1700s.",
  },
  {
    id: "meatballs",
    name: "Swedish Meatballs",
    emoji: "🧆",
    place: "Stockholm, Sweden",
    country: "Sweden",
    lat: 59.33,
    lon: 18.07,
    fact: "In 2018 Sweden's official account admitted the recipe likely came home with a king who visited Türkiye.",
  },
  {
    id: "smorrebrod",
    name: "Smørrebrød",
    emoji: "🥪",
    place: "Copenhagen, Denmark",
    country: "Denmark",
    lat: 55.68,
    lon: 12.57,
    fact: "Denmark's open-faced sandwich is eaten with a knife and fork — never with your hands.",
  },
  {
    id: "fondue",
    name: "Cheese Fondue",
    emoji: "🧀",
    place: "The Alps, Switzerland",
    country: "Switzerland",
    lat: 46.8,
    lon: 8.23,
    fact: "Swiss mountain villagers melted their hard winter cheese to make it easier to eat — and dipping bread became a national sport.",
  },
  {
    id: "schnitzel",
    name: "Wiener Schnitzel",
    emoji: "🍖",
    place: "Vienna, Austria",
    country: "Austria",
    lat: 48.21,
    lon: 16.37,
    fact: "'Wiener' means 'from Vienna' — by law in Austria, a true one must be made of veal.",
  },
  {
    id: "pretzel",
    name: "Pretzel",
    emoji: "🥨",
    place: "Munich, Germany",
    country: "Germany",
    lat: 48.14,
    lon: 11.58,
    fact: "Legend credits monks who twisted dough to look like arms folded in prayer; Bavaria made it an icon.",
  },
  {
    id: "stroopwafel",
    name: "Stroopwafel",
    emoji: "🧇",
    place: "Gouda, Netherlands",
    country: "Netherlands",
    lat: 52.01,
    lon: 4.71,
    fact: "Invented in Gouda — the trick is resting it on top of a hot drink so the caramel middle goes gooey.",
  },
  {
    id: "waffles",
    name: "Belgian Waffles",
    emoji: "🧇",
    place: "Brussels, Belgium",
    country: "Belgium",
    lat: 50.85,
    lon: 4.35,
    fact: "Belgium has two rival waffles — the light rectangular Brussels and the chewy caramelized Liège.",
  },
  {
    id: "moussaka",
    name: "Moussaka",
    emoji: "🍆",
    place: "Athens, Greece",
    country: "Greece",
    lat: 37.98,
    lon: 23.73,
    fact: "The layered eggplant bake got its famous creamy top in the 1920s from Greek chef Nikolaos Tselementes.",
  },
  {
    id: "borscht",
    name: "Borscht",
    emoji: "🍜",
    place: "Kyiv, Ukraine",
    country: "Ukraine",
    lat: 50.45,
    lon: 30.52,
    fact: "Ukraine's beet soup is so treasured that UNESCO added its cooking culture to the world heritage list.",
  },
  {
    id: "goulash",
    name: "Goulash",
    emoji: "🐂",
    place: "Budapest, Hungary",
    country: "Hungary",
    lat: 47.5,
    lon: 19.04,
    fact: "It began as a herdsman's kettle stew on the Hungarian plains — 'gulyás' literally means cowboy.",
  },
  {
    id: "pastel-de-nata",
    name: "Pastel de Nata",
    emoji: "🥧",
    place: "Lisbon, Portugal",
    country: "Portugal",
    lat: 38.72,
    lon: -9.14,
    fact: "Monks in Lisbon invented these custard tarts, and the original 1837 bakery still keeps its recipe secret.",
  },
  {
    id: "skyr",
    name: "Skyr",
    emoji: "🥛",
    place: "Reykjavík, Iceland",
    country: "Iceland",
    lat: 64.15,
    lon: -21.94,
    fact: "Vikings brought this thick, creamy dairy to Iceland over 1,000 years ago — it's technically a soft cheese.",
  },
  {
    id: "shakshuka",
    name: "Shakshuka",
    emoji: "🍳",
    place: "Tunis, Tunisia",
    country: "Tunisia",
    lat: 36.81,
    lon: 10.18,
    fact: "Eggs poached in spiced tomato sauce — the name comes from North African Arabic for 'all mixed up.'",
  },
  {
    id: "nyama-choma",
    name: "Nyama Choma",
    emoji: "🍖",
    place: "Nairobi, Kenya",
    country: "Kenya",
    lat: -1.29,
    lon: 36.82,
    fact: "Kenya's favorite grilled meat is a social event — it's shared straight off the cutting board with friends.",
  },
  {
    id: "piri-piri",
    name: "Piri-Piri Chicken",
    emoji: "🌶️",
    place: "Maputo, Mozambique",
    country: "Mozambique",
    lat: -25.97,
    lon: 32.57,
    fact: "It was born where Portuguese sailors met Mozambique's fiery bird's-eye chili — 'piri-piri' means pepper-pepper.",
  },
  {
    id: "fufu",
    name: "Fufu",
    emoji: "🍠",
    place: "Accra, Ghana",
    country: "Ghana",
    lat: 5.6,
    lon: -0.19,
    fact: "Pounded cassava and plantain, stretched like dough — you pinch off a piece and scoop soup with it.",
  },
  {
    id: "poke",
    name: "Poke",
    emoji: "🐡",
    place: "Honolulu, Hawaii",
    country: "United States of America",
    lat: 21.31,
    lon: -157.86,
    fact: "Hawaiian fishers seasoned fresh-caught fish right on the boat — 'poke' means 'to slice' in Hawaiian.",
  },
  {
    id: "texas-bbq",
    name: "Texas BBQ Brisket",
    emoji: "🤠",
    place: "Austin, Texas, USA",
    country: "United States of America",
    lat: 30.27,
    lon: -97.74,
    fact: "Central Texas pitmasters smoke brisket for up to 18 hours — the best joints sell out by lunchtime.",
  },
  {
    id: "key-lime-pie",
    name: "Key Lime Pie",
    emoji: "🥧",
    place: "Key West, Florida, USA",
    country: "United States of America",
    lat: 24.56,
    lon: -81.78,
    fact: "It's named for the tiny, extra-tart limes that grow in the Florida Keys — and it's Florida's official state pie.",
  },
  {
    id: "jerk-chicken",
    name: "Jerk Chicken",
    emoji: "🔥",
    place: "Kingston, Jamaica",
    country: "Jamaica",
    lat: 17.97,
    lon: -76.79,
    fact: "The smoky-spicy 'jerk' technique was created by Jamaica's Maroons, who cooked over pimento wood.",
  },
  {
    id: "mole",
    name: "Mole Poblano",
    emoji: "🍫",
    place: "Puebla, Mexico",
    country: "Mexico",
    lat: 19.04,
    lon: -98.2,
    fact: "This rich sauce can have more than 20 ingredients — including chocolate and chiles together.",
  },
  {
    id: "ropa-vieja",
    name: "Ropa Vieja",
    emoji: "🥘",
    place: "Havana, Cuba",
    country: "Cuba",
    lat: 23.11,
    lon: -82.37,
    fact: "The name means 'old clothes' — the shredded beef is supposed to look like torn-up rags. Yum?",
  },
  {
    id: "pupusa",
    name: "Pupusas",
    emoji: "🫓",
    place: "San Salvador, El Salvador",
    country: "El Salvador",
    lat: 13.69,
    lon: -89.22,
    fact: "El Salvador's stuffed corn cakes are so beloved there's a national Pupusa Day every November.",
  },
  {
    id: "arepa",
    name: "Arepas",
    emoji: "🌽",
    place: "Caracas, Venezuela",
    country: "Venezuela",
    lat: 10.48,
    lon: -66.9,
    fact: "These grilled corn pockets have been made for thousands of years — Venezuela and Colombia both call them their own.",
  },
  {
    id: "empanada",
    name: "Empanadas",
    emoji: "🥟",
    place: "Salta, Argentina",
    country: "Argentina",
    lat: -24.79,
    lon: -65.41,
    fact: "The idea sailed over from Galicia in Spain, but Argentina's provinces each bake their own proud version.",
  },
  {
    id: "gelato",
    name: "Gelato",
    emoji: "🍨",
    place: "Florence, Italy",
    country: "Italy",
    lat: 43.77,
    lon: 11.26,
    fact: "Renaissance Florence gets the credit — an architect named Buontalenti wowed the Medici court with it.",
  },
  {
    id: "crepes",
    name: "Crêpes",
    emoji: "🥞",
    place: "Brittany, France",
    country: "France",
    lat: 48.11,
    lon: -1.68,
    fact: "They come from Brittany, where buckwheat crêpes are savory and there's even a holiday for flipping them.",
  },
  {
    id: "churros",
    name: "Churros",
    emoji: "🍩",
    place: "Madrid, Spain",
    country: "Spain",
    lat: 40.42,
    lon: -3.7,
    fact: "In Madrid the classic move is dunking them in thick hot chocolate — sometimes for breakfast.",
  },
  {
    id: "ramen",
    name: "Tonkotsu Ramen",
    emoji: "🍥",
    place: "Fukuoka, Japan",
    country: "Japan",
    lat: 33.59,
    lon: 130.4,
    fact: "Fukuoka's creamy pork-bone ramen simmers for many hours — the city has entire streets of ramen stalls.",
  },
  {
    id: "dim-sum",
    name: "Dim Sum",
    emoji: "🥢",
    place: "Guangzhou, China",
    country: "China",
    lat: 23.13,
    lon: 113.26,
    fact: "It grew out of Guangzhou's tea houses, where travelers snacked on little baskets of dumplings with their tea.",
  },
  {
    id: "laksa",
    name: "Laksa",
    emoji: "🦐",
    place: "Singapore",
    country: "Singapore",
    lat: 1.35,
    lon: 103.82,
    fact: "This spicy coconut noodle soup was born where Chinese and Malay cooking met along the old trade routes.",
  },
  {
    id: "nasi-goreng",
    name: "Nasi Goreng",
    emoji: "🍛",
    place: "Jakarta, Indonesia",
    country: "Indonesia",
    lat: -6.21,
    lon: 106.85,
    fact: "Indonesia's 'fried rice' is a genius way to use yesterday's rice — many eat it for breakfast with a fried egg on top.",
  },
  {
    id: "adobo",
    name: "Chicken Adobo",
    emoji: "🍗",
    place: "Manila, Philippines",
    country: "Philippines",
    lat: 14.6,
    lon: 120.98,
    fact: "Filipinos were braising meat in vinegar and soy long before the Spanish arrived and gave it the name adobo.",
  },
  {
    id: "momo",
    name: "Momos",
    emoji: "🏔️",
    place: "Kathmandu, Nepal",
    country: "Nepal",
    lat: 27.72,
    lon: 85.32,
    fact: "These Himalayan dumplings traveled the mountain passes with Tibetan and Newari traders — now they're Nepal's favorite snack.",
  },
  {
    id: "biryani",
    name: "Biryani",
    emoji: "🍚",
    place: "Hyderabad, India",
    country: "India",
    lat: 17.39,
    lon: 78.49,
    fact: "Hyderabad's famous version cooks the rice and meat together sealed under a dough lid so no steam escapes.",
  },
  {
    id: "xiaolongbao",
    name: "Xiaolongbao",
    emoji: "🥟",
    place: "Shanghai, China",
    country: "China",
    lat: 31.23,
    lon: 121.47,
    fact: "These 'soup dumplings' hide hot broth inside — the secret is jellied stock that melts as they steam.",
  },
  {
    id: "plov",
    name: "Plov",
    emoji: "🥕",
    place: "Tashkent, Uzbekistan",
    country: "Uzbekistan",
    lat: 41.3,
    lon: 69.24,
    fact: "Uzbekistan's rice feast is cooked by masters in giant pots called kazans — one pot can feed hundreds.",
  },
  {
    id: "khachapuri",
    name: "Khachapuri",
    emoji: "⛵",
    place: "Tbilisi, Georgia",
    country: "Georgia",
    lat: 41.72,
    lon: 44.79,
    fact: "Georgia's cheese bread comes boat-shaped with an egg on top — you stir it all together and tear off the crust to dip.",
  },
  {
    id: "tahdig",
    name: "Tahdig",
    emoji: "🍚",
    place: "Tehran, Iran",
    country: "Iran",
    lat: 35.69,
    lon: 51.39,
    fact: "Persian cooks compete over this golden crispy rice from the bottom of the pot — the name means 'bottom of the pot.'",
  },
  {
    id: "kabsa",
    name: "Kabsa",
    emoji: "🍗",
    place: "Riyadh, Saudi Arabia",
    country: "Saudi Arabia",
    lat: 24.71,
    lon: 46.68,
    fact: "Saudi Arabia's spiced rice platter is made for sharing — everyone gathers around one big dish.",
  },
  {
    id: "mansaf",
    name: "Mansaf",
    emoji: "🐑",
    place: "Amman, Jordan",
    country: "Jordan",
    lat: 31.95,
    lon: 35.93,
    fact: "Jordan's national dish uses a tangy dried-yogurt sauce called jameed, and it's traditionally eaten with the right hand.",
  },
  {
    id: "pelmeni",
    name: "Pelmeni",
    emoji: "❄️",
    place: "Ural Mountains, Russia",
    country: "Russia",
    lat: 56.84,
    lon: 60.61,
    fact: "Siberian families made these little dumplings by the hundreds and froze them outside in the snow.",
  },
  {
    id: "banh-mi",
    name: "Bánh Mì",
    emoji: "🥖",
    place: "Ho Chi Minh City, Vietnam",
    country: "Vietnam",
    lat: 10.82,
    lon: 106.63,
    fact: "It mixes a French baguette with Vietnamese fillings — a mashup from when France occupied Vietnam.",
  },
  {
    id: "char-kway-teow",
    name: "Char Kway Teow",
    emoji: "🍤",
    place: "Penang, Malaysia",
    country: "Malaysia",
    lat: 5.42,
    lon: 100.33,
    fact: "Penang's smoky fried noodles get their flavor from 'wok hei' — the breath of a blazing-hot wok.",
  },
  {
    id: "pavlova",
    name: "Pavlova",
    emoji: "🍓",
    place: "Wellington, New Zealand",
    country: "New Zealand",
    lat: -41.29,
    lon: 174.78,
    fact: "Named for a visiting ballerina — New Zealand and Australia have argued for a century over who invented it.",
  },
  {
    id: "meat-pie",
    name: "Meat Pie",
    emoji: "🥧",
    place: "Sydney, Australia",
    country: "Australia",
    lat: -33.87,
    lon: 151.21,
    fact: "Australians eat about 270 million of these hand-sized pies a year — it's the classic footy-stadium snack.",
  },
  {
    id: "lamington",
    name: "Lamingtons",
    emoji: "🍰",
    place: "Brisbane, Australia",
    country: "Australia",
    lat: -27.47,
    lon: 153.03,
    fact: "Sponge cake dipped in chocolate and coconut, supposedly named after a Queensland governor, Lord Lamington.",
  },
  {
    id: "kokoda",
    name: "Kokoda",
    emoji: "🥥",
    place: "Suva, Fiji",
    country: "Fiji",
    lat: -18.14,
    lon: 178.44,
    fact: "Fiji's answer to ceviche — fresh fish cured in lime and served swimming in coconut cream.",
  },
  // ── expansion wave (daily-pool build-out) ──────────────────────────────
  { id: "tom-yum", name: "Tom Yum Goong", place: "Bangkok, Thailand", country: "Thailand", lat: 13.76, lon: 100.5, fact: "Thailand's hot-and-sour shrimp soup balances four flavors at once — spicy, sour, salty, and sweet — with lemongrass and lime leaf." },
  { id: "som-tam", name: "Som Tam", place: "Isaan, Thailand", country: "Thailand", lat: 16.43, lon: 102.84, fact: "Green papaya salad from Thailand's northeast, pounded to order in a clay mortar — you can hear it being made from down the street." },
  { id: "khao-soi", name: "Khao Soi", place: "Chiang Mai, Thailand", country: "Thailand", lat: 18.79, lon: 98.98, fact: "Northern Thailand's curry noodle soup tops soft noodles with a crunchy nest of the same noodles, fried." },
  { id: "bun-cha", name: "Bún Chả", place: "Hanoi, Vietnam", country: "Vietnam", lat: 21.03, lon: 105.85, fact: "Hanoi's grilled-pork noodle lunch got world-famous when Anthony Bourdain shared a bowl with President Obama on plastic stools." },
  { id: "rendang", name: "Rendang", place: "Padang, Indonesia", country: "Indonesia", lat: -0.95, lon: 100.35, fact: "The Minangkabau people slow-cook beef in coconut milk for hours until nearly dry — it was made to survive long journeys without a fridge." },
  { id: "satay", name: "Satay", place: "Java, Indonesia", country: "Indonesia", lat: -7.87, lon: 111.46, fact: "Skewered street meat born on Java, now grilled from Jakarta to Amsterdam — the peanut sauce is the part people argue about." },
  { id: "gado-gado", name: "Gado-Gado", place: "Jakarta, Indonesia", country: "Indonesia", lat: -6.21, lon: 106.85, fact: "The name roughly means 'mix-mix' — a salad of blanched vegetables and tofu drowned in warm peanut dressing." },
  { id: "sisig", name: "Sisig", place: "Angeles City, Philippines", country: "Philippines", lat: 15.15, lon: 120.58, fact: "Born in Pampanga, the Philippines' sizzling chopped-pork plate arrives at the table still crackling on a hot iron dish." },
  { id: "halo-halo", name: "Halo-Halo", place: "Manila, Philippines", country: "Philippines", lat: 14.6, lon: 120.98, fact: "'Mix-mix' in Tagalog: shaved ice layered with sweet beans, jellies, milk, and purple ube ice cream — you stir it all together before eating." },
  { id: "chicken-rice", name: "Hainanese Chicken Rice", place: "Singapore", country: "Singapore", lat: 1.35, lon: 103.82, fact: "Brought by Hainanese immigrants and perfected in Singapore's hawker centres, where a plate can cost less than a bus ride." },
  { id: "chilli-crab", name: "Chilli Crab", place: "Singapore", country: "Singapore", lat: 1.29, lon: 103.85, fact: "Singapore's most famous seafood dish was invented in the 1950s by a street vendor who tossed crab in sweet chili-tomato sauce." },
  { id: "nasi-lemak", name: "Nasi Lemak", place: "Kuala Lumpur, Malaysia", country: "Malaysia", lat: 3.14, lon: 101.69, fact: "Malaysia's coconut rice breakfast comes wrapped in a banana leaf with sambal, crispy anchovies, peanuts, and egg." },
  { id: "roti-canai", name: "Roti Canai", place: "Kuala Lumpur, Malaysia", country: "Malaysia", lat: 3.14, lon: 101.69, fact: "Flaky flatbread flipped and stretched paper-thin in the air, brought to Malaysia by Indian Muslim cooks — dipped in dhal or curry." },
  { id: "mango-sticky-rice", name: "Mango Sticky Rice", place: "Bangkok, Thailand", country: "Thailand", lat: 13.76, lon: 100.5, fact: "Thailand's beloved dessert pairs ripe mango with coconut-soaked glutinous rice — best in April, peak mango season." },
  { id: "bibimbap", name: "Bibimbap", place: "Jeonju, South Korea", country: "South Korea", lat: 35.82, lon: 127.15, fact: "The city of Jeonju is so proud of its rice-bowl-with-everything that UNESCO named it a City of Gastronomy." },
  { id: "tteokbokki", name: "Tteokbokki", place: "Seoul, South Korea", country: "South Korea", lat: 37.57, lon: 126.98, fact: "Chewy rice cakes in glossy red gochujang sauce — Seoul's favorite after-school street snack." },
  { id: "kfc-korean", name: "Korean Fried Chicken", place: "Seoul, South Korea", country: "South Korea", lat: 37.57, lon: 126.98, fact: "Double-fried for an extra-thin, extra-crackly crust, then painted with sweet-spicy glaze — 'chimaek' means eating it with friends." },
  { id: "okonomiyaki", name: "Okonomiyaki", place: "Osaka, Japan", country: "Japan", lat: 34.69, lon: 135.5, fact: "Osaka's savory 'cook-what-you-like' pancake is griddled at your table and painted with sauce, mayo, and dancing bonito flakes." },
  { id: "takoyaki", name: "Takoyaki", place: "Osaka, Japan", country: "Japan", lat: 34.69, lon: 135.5, fact: "Molten octopus-filled batter balls flipped with picks in special dimpled pans — an Osaka street invention from 1935." },
  { id: "tempura", name: "Tempura", place: "Tokyo, Japan", country: "Japan", lat: 35.68, lon: 139.69, fact: "The feather-light frying technique came to Japan with Portuguese missionaries in the 1500s, then Edo perfected it." },
  { id: "udon", name: "Sanuki Udon", place: "Kagawa, Japan", country: "Japan", lat: 34.34, lon: 134.05, fact: "Kagawa prefecture is Japan's udon heartland — thick chewy noodles so beloved the local airport greets you with udon shops." },
  { id: "hot-pot", name: "Chongqing Hot Pot", place: "Chongqing, China", country: "China", lat: 29.56, lon: 106.55, fact: "A bubbling cauldron of chili-and-numbing-peppercorn broth — Chongqing has more hot pot restaurants than any city on Earth." },
  { id: "mapo-tofu", name: "Mapo Tofu", place: "Chengdu, China", country: "China", lat: 30.57, lon: 104.07, fact: "Named after the pockmarked grandmother who ran a Chengdu restaurant in the 1800s and invented it for hungry laborers." },
  { id: "kung-pao", name: "Kung Pao Chicken", place: "Chengdu, China", country: "China", lat: 30.57, lon: 104.07, fact: "Named for a Qing-dynasty governor of Sichuan whose title was 'Gongbao' — the real version numbs your lips with Sichuan peppercorns." },
  { id: "lanzhou-noodles", name: "Lanzhou Beef Noodles", place: "Lanzhou, China", country: "China", lat: 36.06, lon: 103.83, fact: "Masters hand-pull a single lump of dough into needle-thin noodles in seconds — the broth recipe dates to 1915." },
  { id: "char-siu", name: "Char Siu", place: "Guangzhou, China", country: "China", lat: 23.13, lon: 113.26, fact: "Cantonese barbecued pork lacquered red with honey and spices, hung in shop windows across Guangzhou and Hong Kong." },
  { id: "buuz", name: "Buuz", place: "Ulaanbaatar, Mongolia", country: "Mongolia", lat: 47.89, lon: 106.91, fact: "Mongolian steamed mutton dumplings eaten by the dozen during Tsagaan Sar, the lunar new year — families make thousands in advance." },
  { id: "masala-dosa", name: "Masala Dosa", place: "Udupi, India", country: "India", lat: 13.34, lon: 74.75, fact: "The crispy fermented crepe with spiced potato filling spread across India from Udupi's temple kitchens." },
  { id: "vada-pav", name: "Vada Pav", place: "Mumbai, India", country: "India", lat: 19.08, lon: 72.88, fact: "Mumbai's spicy potato fritter in a bun — invented outside a train station in 1966 and still the city's favorite one-hand lunch." },
  { id: "chole-bhature", name: "Chole Bhature", place: "Delhi, India", country: "India", lat: 28.61, lon: 77.21, fact: "Spiced chickpeas with a balloon of fried bread — a Delhi and Punjabi breakfast that demands a nap afterward." },
  { id: "rogan-josh", name: "Rogan Josh", place: "Srinagar, India", country: "India", lat: 34.08, lon: 74.8, fact: "The crown of Kashmiri cooking: lamb stewed brick-red with Kashmiri chilies, milder than its color warns." },
  { id: "samosa", name: "Samosa", place: "Delhi, India", country: "India", lat: 28.61, lon: 77.21, fact: "The stuffed triangle traveled to India from Central Asia with medieval traders — the potato filling came later and conquered all." },
  { id: "nihari", name: "Nihari", place: "Old Delhi, India", country: "India", lat: 28.66, lon: 77.23, fact: "A slow-simmered overnight stew once served to Mughal nobles at sunrise — the name comes from 'nihar', Arabic for morning." },
  { id: "kottu", name: "Kottu Roti", place: "Colombo, Sri Lanka", country: "Sri Lanka", lat: 6.93, lon: 79.86, fact: "Sri Lanka's favorite late-night food: chopped flatbread stir-fried with curry on a steel griddle — cooks drum the blades like a percussion solo." },
  { id: "karahi", name: "Chicken Karahi", place: "Peshawar, Pakistan", country: "Pakistan", lat: 34.01, lon: 71.58, fact: "Cooked fast in the wok-like pan it's named for, with tomatoes, ginger, and green chili — Peshawar's karahi houses sell it by the kilo." },
  { id: "beshbarmak", name: "Beshbarmak", place: "Almaty, Kazakhstan", country: "Kazakhstan", lat: 43.24, lon: 76.89, fact: "'Five fingers' — the Kazakh national dish of boiled meat over wide noodles, traditionally eaten by hand at celebrations." },
  { id: "khinkali", name: "Khinkali", place: "Tbilisi, Georgia", country: "Georgia", lat: 41.72, lon: 44.79, fact: "Georgian soup dumplings with a doughy topknot handle — you're not supposed to eat the knot, and spilling the broth is a rookie mistake." },
  { id: "dolma", name: "Dolma", place: "Baku, Azerbaijan", country: "Azerbaijan", lat: 40.41, lon: 49.87, fact: "Grape leaves wrapped around spiced rice and meat — Azerbaijan's dolma tradition is on UNESCO's cultural heritage list." },
  { id: "lavash", name: "Lavash", place: "Yerevan, Armenia", country: "Armenia", lat: 40.18, lon: 44.51, fact: "Armenia's paper-thin flatbread is slapped onto the wall of a buried clay oven — the baking tradition is UNESCO-listed." },
  { id: "hummus", name: "Hummus", place: "Beirut, Lebanon", country: "Lebanon", lat: 33.89, lon: 35.5, fact: "Chickpeas, tahini, lemon, and garlic — half the eastern Mediterranean claims it, and the earliest recipes date to medieval Cairo." },
  { id: "tabbouleh", name: "Tabbouleh", place: "Mount Lebanon, Lebanon", country: "Lebanon", lat: 33.89, lon: 35.5, fact: "Born in the Lebanese mountains: a parsley salad with bulgur — not a bulgur salad with parsley, as any Lebanese cook will insist." },
  { id: "falafel", name: "Falafel", place: "Cairo, Egypt", country: "Egypt", lat: 30.04, lon: 31.24, fact: "Egyptians fry theirs from fava beans and call it ta'ameya — most food historians trace the fritter to Egypt before it spread through the Levant." },
  { id: "ful-medames", name: "Ful Medames", place: "Cairo, Egypt", country: "Egypt", lat: 30.04, lon: 31.24, fact: "Slow-stewed fava beans with oil and lemon — Egypt's national breakfast, eaten since the time of the pharaohs." },
  { id: "doner", name: "Döner Kebab", place: "Bursa, Türkiye", country: "Turkey", lat: 40.19, lon: 29.06, fact: "The vertical rotating spit was pioneered in 1800s Bursa — a century later, Turkish workers in Berlin turned it into Europe's favorite sandwich." },
  { id: "lahmacun", name: "Lahmacun", place: "Gaziantep, Türkiye", country: "Turkey", lat: 37.07, lon: 37.38, fact: "A whisper-thin flatbread with spiced minced lamb from Gaziantep, a UNESCO City of Gastronomy — roll it up with parsley and lemon." },
  { id: "kunefe", name: "Künefe", place: "Hatay, Türkiye", country: "Turkey", lat: 36.2, lon: 36.16, fact: "Molten cheese sandwiched in crispy shredded pastry, soaked in syrup, served hot — Hatay province is its Turkish capital." },
  { id: "turkish-delight", name: "Turkish Delight", place: "Istanbul, Türkiye", country: "Turkey", lat: 41.01, lon: 28.98, fact: "Lokum has been made in Istanbul since the 1700s — the confectioner Hacı Bekir's original shop still sells it today." },
  { id: "couscous", name: "Couscous", place: "Algiers, Algeria", country: "Algeria", lat: 36.75, lon: 3.06, fact: "Hand-rolled semolina pearls steamed over stew — a Berber creation so central to North Africa that UNESCO honored it across four countries." },
  { id: "suya", name: "Suya", place: "Kano, Nigeria", country: "Nigeria", lat: 12.0, lon: 8.52, fact: "Northern Nigeria's spicy grilled meat skewers get their kick from yaji — a peanut-and-chili spice blend guarded like a family secret." },
  { id: "egusi", name: "Egusi Soup", place: "Lagos, Nigeria", country: "Nigeria", lat: 6.52, lon: 3.38, fact: "Thickened with ground melon seeds and eaten with pounded yam — one of Nigeria's most beloved soups across all its regions." },
  { id: "thieboudienne", name: "Thieboudienne", place: "Saint-Louis, Senegal", country: "Senegal", lat: 16.03, lon: -16.49, fact: "Senegal's national dish of fish and broken rice was created in Saint-Louis by the cook Penda Mbaye — UNESCO lists it as world heritage." },
  { id: "doro-wat", name: "Doro Wat", place: "Addis Ababa, Ethiopia", country: "Ethiopia", lat: 9.01, lon: 38.75, fact: "Ethiopia's holiday chicken stew simmers in berbere spice and slow-cooked onions for hours — always served on injera with a boiled egg." },
  { id: "matoke", name: "Matoke", place: "Kampala, Uganda", country: "Uganda", lat: 0.35, lon: 32.58, fact: "Green highland bananas steamed in their own leaves and mashed — Uganda grows more bananas per person than almost anywhere." },
  { id: "sadza", name: "Sadza", place: "Harare, Zimbabwe", country: "Zimbabwe", lat: -17.83, lon: 31.05, fact: "Zimbabwe's cornmeal staple is eaten with the right hand, rolled into a ball and dipped into stew — dinner isn't dinner without it." },
  { id: "bobotie", name: "Bobotie", place: "Cape Town, South Africa", country: "South Africa", lat: -33.92, lon: 18.42, fact: "Cape Malay cooks turned spiced minced meat with a golden egg custard top into South Africa's most famous bake." },
  { id: "attieke", name: "Attiéké", place: "Abidjan, Côte d'Ivoire", country: "Côte d'Ivoire", lat: 5.36, lon: -4.01, fact: "Côte d'Ivoire's tangy fermented cassava couscous, piled next to grilled fish — now protected as an official heritage food." },
  { id: "ndole", name: "Ndolé", place: "Douala, Cameroon", country: "Cameroon", lat: 4.05, lon: 9.7, fact: "Cameroon's national dish stews bitterleaf greens with peanuts and shrimp — the bitterness is washed out leaf by leaf, by hand." },
  { id: "pastilla", name: "Pastilla", place: "Fez, Morocco", country: "Morocco", lat: 34.03, lon: -4.98, fact: "Fez's festive pie hides savory pigeon or chicken under crackling pastry dusted with sugar and cinnamon — sweet and savory on purpose." },
  { id: "hot-dog", name: "Hot Dog", place: "New York City, USA", country: "United States of America", lat: 40.71, lon: -74.01, fact: "German immigrants brought the frankfurter; New York's street carts and Coney Island made it America's icon." },
  { id: "hamburger", name: "Hamburger", place: "New Haven, USA", country: "United States of America", lat: 41.31, lon: -72.92, fact: "Named for Hamburg, Germany, but the sandwich is American — Louis' Lunch in New Haven claims the first one, served since 1900." },
  { id: "buffalo-wings", name: "Buffalo Wings", place: "Buffalo, USA", country: "United States of America", lat: 42.89, lon: -78.88, fact: "Invented at the Anchor Bar in Buffalo in 1964, allegedly as a midnight snack for the owner's son and his friends." },
  { id: "gumbo", name: "Gumbo", place: "New Orleans, USA", country: "United States of America", lat: 29.95, lon: -90.07, fact: "Louisiana's melting-pot stew blends West African okra, French roux, and Choctaw filé powder — it's the official state cuisine." },
  { id: "deep-dish", name: "Deep-Dish Pizza", place: "Chicago, USA", country: "United States of America", lat: 41.88, lon: -87.63, fact: "Invented at Pizzeria Uno in 1943 — more pie than pizza, with the sauce famously on top of the cheese." },
  { id: "cheesesteak", name: "Philly Cheesesteak", place: "Philadelphia, USA", country: "United States of America", lat: 39.95, lon: -75.17, fact: "Started at a 1930s hot dog cart when Pat Olivieri grilled beef instead — order 'whiz wit' for Cheez Whiz with onions." },
  { id: "lobster-roll", name: "Lobster Roll", place: "Maine, USA", country: "United States of America", lat: 43.66, lon: -70.26, fact: "Maine piles cold lobster with mayo in a split-top bun; Connecticut serves it warm with butter — the rivalry is real." },
  { id: "montreal-bagel", name: "Montreal Bagel", place: "Montreal, Canada", country: "Canada", lat: 45.5, lon: -73.57, fact: "Smaller, denser, and sweeter than New York's — boiled in honey water and baked in wood-fired ovens that never cool down." },
  { id: "nanaimo-bar", name: "Nanaimo Bar", place: "Nanaimo, Canada", country: "Canada", lat: 49.17, lon: -123.94, fact: "A no-bake chocolate-custard-coconut bar named for the British Columbia city — Canada put it on a postage stamp." },
  { id: "elote", name: "Elote", place: "Mexico City, Mexico", country: "Mexico", lat: 19.43, lon: -99.13, fact: "Street corn slathered with mayo, cheese, chili, and lime — corn has been sacred in Mexico for 9,000 years." },
  { id: "cochinita", name: "Cochinita Pibil", place: "Mérida, Mexico", country: "Mexico", lat: 20.97, lon: -89.62, fact: "Yucatán's achiote-marinated pork, wrapped in banana leaves and roasted in a pit oven — a Maya technique older than the conquest." },
  { id: "chiles-en-nogada", name: "Chiles en Nogada", place: "Puebla, Mexico", country: "Mexico", lat: 19.04, lon: -98.2, fact: "Green chile, white walnut sauce, red pomegranate — the colors of the Mexican flag, created by Puebla nuns for independence celebrations." },
  { id: "gallo-pinto", name: "Gallo Pinto", place: "San José, Costa Rica", country: "Costa Rica", lat: 9.93, lon: -84.08, fact: "'Spotted rooster' rice and beans — Costa Rica and Nicaragua both claim it, and the friendly feud has produced world-record-sized batches." },
  { id: "baleada", name: "Baleada", place: "La Ceiba, Honduras", country: "Honduras", lat: 15.78, lon: -86.79, fact: "A thick flour tortilla folded over refried beans, cream, and cheese — Honduras' go-to meal at any hour." },
  { id: "mofongo", name: "Mofongo", place: "San Juan, Puerto Rico", country: "United States of America", lat: 18.47, lon: -66.11, fact: "Fried green plantains mashed with garlic and chicharrón in a wooden pilón — Puerto Rico's answer to West African fufu." },
  { id: "sancocho", name: "Sancocho", place: "Santo Domingo, Dominican Republic", country: "Dominican Rep.", lat: 18.49, lon: -69.93, fact: "The Dominican Republic's seven-meat celebration stew — making it is an all-day family event, usually for a crowd." },
  { id: "doubles", name: "Doubles", place: "Port of Spain, Trinidad and Tobago", country: "Trinidad and Tobago", lat: 10.65, lon: -61.51, fact: "Two fried barra breads hugging curried chickpeas — invented by an Indo-Trinidadian street vendor in the 1930s, eaten standing up." },
  { id: "griot", name: "Griot", place: "Port-au-Prince, Haiti", country: "Haiti", lat: 18.54, lon: -72.34, fact: "Haiti's celebration pork: marinated in bitter orange, boiled, then fried until crispy — served with fiery pikliz slaw." },
  { id: "bandeja-paisa", name: "Bandeja Paisa", place: "Medellín, Colombia", country: "Colombia", lat: 6.25, lon: -75.56, fact: "Medellín's mountain platter piles beans, rice, chicharrón, sausage, avocado, egg, and more onto one heroic tray." },
  { id: "ajiaco", name: "Ajiaco", place: "Bogotá, Colombia", country: "Colombia", lat: 4.71, lon: -74.07, fact: "Bogotá's chicken-and-three-potato soup owes its flavor to guascas, an Andean herb the Muisca people cooked with long before the Spanish came." },
  { id: "pabellon", name: "Pabellón Criollo", place: "Caracas, Venezuela", country: "Venezuela", lat: 10.48, lon: -66.9, fact: "Venezuela's flag on a plate: shredded beef, black beans, rice, and fried plantains — each stripe a different color." },
  { id: "lomo-saltado", name: "Lomo Saltado", place: "Lima, Peru", country: "Peru", lat: -12.05, lon: -77.04, fact: "Beef stir-fried in a wok with soy sauce AND served with fries and rice — the delicious result of Chinese immigration to Peru." },
  { id: "saltena", name: "Salteña", place: "La Paz, Bolivia", country: "Bolivia", lat: -16.5, lon: -68.15, fact: "Bolivia's juicy morning empanada is filled with stew, not solids — locals judge you by whether you can eat one without spilling." },
  { id: "chivito", name: "Chivito", place: "Montevideo, Uruguay", country: "Uruguay", lat: -34.9, lon: -56.16, fact: "Uruguay's national sandwich stacks steak, ham, bacon, egg, and mozzarella — invented when a customer asked for goat and got this instead." },
  { id: "dulce-de-leche", name: "Dulce de Leche", place: "Buenos Aires, Argentina", country: "Argentina", lat: -34.6, lon: -58.38, fact: "Legend says a distracted cook left sweetened milk on the fire in 1829 and came back to caramel gold — Argentina eats kilos of it per person yearly." },
  { id: "curanto", name: "Curanto", place: "Chiloé, Chile", country: "Chile", lat: -42.48, lon: -73.76, fact: "On Chiloé Island, shellfish and meat steam for hours in a pit of hot stones covered with giant rhubarb leaves — a technique thousands of years old." },
  { id: "pao-de-queijo", name: "Pão de Queijo", place: "Belo Horizonte, Brazil", country: "Brazil", lat: -19.92, lon: -43.94, fact: "Minas Gerais' chewy cheese puffs are made with cassava starch, so they're naturally gluten-free — and dangerously poppable." },
  { id: "moqueca", name: "Moqueca", place: "Salvador, Brazil", country: "Brazil", lat: -12.97, lon: -38.5, fact: "Bahia's fish stew glows orange with dendê palm oil and coconut milk — Espírito Santo state cooks a rival version and the debate never ends." },
  { id: "brigadeiro", name: "Brigadeiro", place: "Rio de Janeiro, Brazil", country: "Brazil", lat: -22.91, lon: -43.17, fact: "Brazil's fudge balls were named after a 1940s brigadier whose presidential campaign sold them — he lost the election, the sweet won forever." },
  { id: "carbonara", name: "Carbonara", place: "Rome, Italy", country: "Italy", lat: 41.9, lon: 12.5, fact: "Eggs, guanciale, pecorino, pepper — nothing else. Rome polices the recipe so fiercely that adding cream can make headlines." },
  { id: "risotto-milanese", name: "Risotto alla Milanese", place: "Milan, Italy", country: "Italy", lat: 45.46, lon: 9.19, fact: "Milan's golden risotto gets its color from saffron — legend credits a glassmaker's apprentice who tinted rice at a 1574 wedding as a joke." },
  { id: "pesto", name: "Pesto alla Genovese", place: "Genoa, Italy", country: "Italy", lat: 44.41, lon: 8.93, fact: "Genoa's basil sauce is properly made in a marble mortar — 'pesto' literally means 'pounded'." },
  { id: "arancini", name: "Arancini", place: "Palermo, Italy", country: "Italy", lat: 38.12, lon: 13.36, fact: "Sicily's fried rice balls are named 'little oranges' for their shape — Palermo and Catania still argue over cone versus sphere." },
  { id: "tiramisu", name: "Tiramisù", place: "Treviso, Italy", country: "Italy", lat: 45.67, lon: 12.24, fact: "'Pick-me-up' in Italian — the coffee-and-mascarpone dessert was born in a Treviso restaurant in the late 1960s, newer than you'd guess." },
  { id: "ratatouille", name: "Ratatouille", place: "Nice, France", country: "France", lat: 43.7, lon: 7.27, fact: "Once a humble summer-vegetable stew of Provençal farmers — a Pixar rat made it the most famous French dish on Earth." },
  { id: "bouillabaisse", name: "Bouillabaisse", place: "Marseille, France", country: "France", lat: 43.3, lon: 5.37, fact: "Marseille fishermen's stew of the unsold catch became so prized the city wrote a charter defining what may bear the name." },
  { id: "quiche", name: "Quiche Lorraine", place: "Nancy, France", country: "France", lat: 48.69, lon: 6.18, fact: "From the Lorraine region on the German border — the original had no cheese, just eggs, cream, and smoky bacon in pastry." },
  { id: "tarte-tatin", name: "Tarte Tatin", place: "Lamotte-Beuvron, France", country: "France", lat: 47.6, lon: 1.99, fact: "The Tatin sisters supposedly botched an apple pie at their hotel, baked it upside down anyway, and created a French classic." },
  { id: "macaron", name: "Macaron", place: "Paris, France", country: "France", lat: 48.86, lon: 2.35, fact: "Catherine de' Medici's Italian pastry cooks brought the almond cookie to France — Paris' Ladurée invented the double-decker version in 1930." },
  { id: "gazpacho", name: "Gazpacho", place: "Seville, Spain", country: "Spain", lat: 37.39, lon: -5.99, fact: "Andalusia's cold tomato soup began as a field workers' blend of stale bread, oil, and vinegar — tomatoes joined only after they arrived from the Americas." },
  { id: "tortilla", name: "Tortilla Española", place: "Navarra, Spain", country: "Spain", lat: 42.82, lon: -1.64, fact: "Spain's thick potato omelette sparks a national debate: with onion or without? Entire polls have been run on it." },
  { id: "pintxos", name: "Pintxos", place: "San Sebastián, Spain", country: "Spain", lat: 43.32, lon: -1.98, fact: "The Basque country's skewered bar snacks — you graze from bar to bar, and they count your toothpicks to tally the bill." },
  { id: "francesinha", name: "Francesinha", place: "Porto, Portugal", country: "Portugal", lat: 41.15, lon: -8.61, fact: "Porto's 'little French girl': a sandwich of meats buried under melted cheese and spicy beer sauce — invented by a returning emigrant in the 1950s." },
  { id: "full-english", name: "Full English Breakfast", place: "London, England", country: "United Kingdom", lat: 51.51, lon: -0.13, fact: "Eggs, bacon, sausage, beans, toast, mushrooms, tomato — a plate so institutional that cafes are judged on it alone." },
  { id: "cornish-pasty", name: "Cornish Pasty", place: "Cornwall, England", country: "United Kingdom", lat: 50.26, lon: -5.05, fact: "Cornish miners carried these crimped pies underground — the thick crust edge was a handle for dirty hands, then thrown away." },
  { id: "cawl", name: "Cawl", place: "Cardiff, Wales", country: "United Kingdom", lat: 51.48, lon: -3.18, fact: "Wales' national broth of lamb and leeks, simmered slow — many say it tastes best reheated the next day." },
  { id: "moules-frites", name: "Moules-Frites", place: "Brussels, Belgium", country: "Belgium", lat: 50.85, lon: 4.35, fact: "Belgium's mussels-and-fries pairing goes back centuries — Belgians eat them using an empty mussel shell as tweezers." },
  { id: "bitterballen", name: "Bitterballen", place: "Amsterdam, Netherlands", country: "Netherlands", lat: 52.37, lon: 4.9, fact: "Crispy fried balls of molten beef ragout, served with mustard at every Dutch bar — the inside stays lava-hot, be warned." },
  { id: "currywurst", name: "Currywurst", place: "Berlin, Germany", country: "Germany", lat: 52.52, lon: 13.4, fact: "In 1949 Berlin, Herta Heuwer mixed ketchup with curry powder from British soldiers and poured it over sausage — a city icon was born." },
  { id: "sauerbraten", name: "Sauerbraten", place: "Cologne, Germany", country: "Germany", lat: 50.94, lon: 6.96, fact: "Germany's 'sour roast' marinates beef in vinegar and spices for days — Rhineland versions sweeten the gravy with raisins." },
  { id: "black-forest", name: "Black Forest Gateau", place: "Black Forest, Germany", country: "Germany", lat: 48.3, lon: 8.2, fact: "Chocolate, cherries, cream, and real kirsch brandy — German law says a true Schwarzwälder Kirschtorte must contain the kirsch." },
  { id: "rosti", name: "Rösti", place: "Bern, Switzerland", country: "Switzerland", lat: 46.95, lon: 7.45, fact: "Once a Bernese farmer's breakfast of crispy grated potatoes — the 'Röstigraben' now jokingly names the cultural line between German- and French-speaking Switzerland." },
  { id: "raclette", name: "Raclette", place: "Valais, Switzerland", country: "Switzerland", lat: 46.23, lon: 7.36, fact: "Alpine herders melted the cut face of a cheese wheel by the fire and scraped it over potatoes — 'racler' means to scrape." },
  { id: "sachertorte", name: "Sachertorte", place: "Vienna, Austria", country: "Austria", lat: 48.21, lon: 16.37, fact: "Invented by 16-year-old apprentice Franz Sacher in 1832 — Vienna later fought a seven-year court battle over the 'original' recipe." },
  { id: "svickova", name: "Svíčková", place: "Prague, Czechia", country: "Czechia", lat: 50.08, lon: 14.44, fact: "Czech beef in silky root-vegetable cream sauce with dumplings, cranberries, and a puff of whipped cream — Sunday lunch royalty." },
  { id: "langos", name: "Lángos", place: "Budapest, Hungary", country: "Hungary", lat: 47.5, lon: 19.04, fact: "Hungary's deep-fried bread slab rubbed with garlic and loaded with sour cream and cheese — the smell owns every summer festival." },
  { id: "zurek", name: "Żurek", place: "Warsaw, Poland", country: "Poland", lat: 52.23, lon: 21.01, fact: "Poland's sour rye soup with sausage and egg, often served inside a hollowed bread loaf — the tang comes from fermented rye starter." },
  { id: "chicken-kyiv", name: "Chicken Kyiv", place: "Kyiv, Ukraine", country: "Ukraine", lat: 50.45, lon: 30.52, fact: "A breaded cutlet wrapped around a core of herb butter that bursts when cut — cut carefully, the butter has ruined many shirts." },
  { id: "cevapi", name: "Ćevapi", place: "Sarajevo, Bosnia and Herzegovina", country: "Bosnia and Herz.", lat: 43.86, lon: 18.41, fact: "Sarajevo's little grilled beef fingers arrive in somun flatbread with raw onion — ordering fewer than five is considered odd." },
  { id: "burek", name: "Burek", place: "Sarajevo, Bosnia and Herzegovina", country: "Bosnia and Herz.", lat: 43.86, lon: 18.41, fact: "Coiled phyllo pie from the Ottoman world — in Bosnia only the meat one is 'burek'; call a cheese pie burek and locals will correct you." },
  { id: "gyros", name: "Gyros", place: "Athens, Greece", country: "Greece", lat: 37.98, lon: 23.73, fact: "Greece's spit-roasted pork in pita with tzatziki — the name just means 'turn', for the rotating spit." },
  { id: "sarmale", name: "Sarmale", place: "Bucharest, Romania", country: "Romania", lat: 44.43, lon: 26.1, fact: "Romania's cabbage rolls simmer for hours and taste even better the next day — no Christmas or wedding happens without them." },
  { id: "banitsa", name: "Banitsa", place: "Sofia, Bulgaria", country: "Bulgaria", lat: 42.7, lon: 23.32, fact: "Bulgaria's cheese-filled phyllo pastry hides lucky charms on New Year's morning — your slice predicts your year." },
  { id: "kanelbulle", name: "Kanelbulle", place: "Stockholm, Sweden", country: "Sweden", lat: 59.33, lon: 18.07, fact: "Sweden's cardamom-scented cinnamon bun has its own national day, October 4th — fika without one is barely fika." },
  { id: "farikal", name: "Fårikål", place: "Oslo, Norway", country: "Norway", lat: 59.91, lon: 10.75, fact: "Norway's national dish is just lamb, cabbage, and whole peppercorns simmered patiently — it even has a feast day each September." },
  { id: "brunost", name: "Brunost", place: "Gudbrandsdalen, Norway", country: "Norway", lat: 61.5, lon: 9.5, fact: "Norway's caramel-colored 'brown cheese' is made by boiling whey until it caramelizes — sliced thin over waffles with a cheese plane, a Norwegian invention." },
  { id: "karelian-pasty", name: "Karelian Pasty", place: "North Karelia, Finland", country: "Finland", lat: 62.6, lon: 29.76, fact: "Finland's rye-crusted rice pastries from Karelia are topped with egg butter — grandmothers crimp the edges at astonishing speed." },
  { id: "olivier-salad", name: "Olivier Salad", place: "Moscow, Russia", country: "Russia", lat: 55.75, lon: 37.62, fact: "Invented at Moscow's Hermitage restaurant in the 1860s by chef Lucien Olivier, who took the original dressing recipe to his grave." },
  { id: "hangi", name: "Hāngī", place: "Rotorua, New Zealand", country: "New Zealand", lat: -38.14, lon: 176.25, fact: "The Māori earth oven: food steams for hours over heated stones buried in the ground — in Rotorua, geothermal steam does the work." },
  { id: "anzac-biscuit", name: "Anzac Biscuit", place: "Melbourne, Australia", country: "Australia", lat: -37.81, lon: 144.96, fact: "Oat-and-golden-syrup biscuits tied to WWI soldiers' care packages — Australia and New Zealand share this one without fighting, mostly." },
  { id: "poisson-cru", name: "Poisson Cru", place: "Papeete, French Polynesia", country: "France", lat: -17.55, lon: -149.56, fact: "Tahiti's raw tuna in lime and fresh-squeezed coconut milk — fishermen make it on the boat with seawater." },
  { id: "palusami", name: "Palusami", place: "Apia, Samoa", country: "Samoa", lat: -13.83, lon: -171.77, fact: "Young taro leaves wrapped around coconut cream and baked in a Samoan umu — creamy, smoky, and worth burning your fingers for." },
  { id: "laplap", name: "Laplap", place: "Port Vila, Vanuatu", country: "Vanuatu", lat: -17.73, lon: 168.32, fact: "Vanuatu's national dish: grated root vegetables and coconut cream baked in banana leaves under hot stones." },
  { id: "ghormeh-sabzi", name: "Ghormeh Sabzi", place: "Tehran, Iran", country: "Iran", lat: 35.69, lon: 51.39, fact: "Iran's beloved herb stew simmers mountains of sautéed greens with dried limes that pack a sour punch — many call it the national dish." },
  { id: "masgouf", name: "Masgouf", place: "Baghdad, Iraq", country: "Iraq", lat: 33.31, lon: 44.36, fact: "Iraq's riverside classic: carp split open and slow-grilled upright beside a wood fire, a tradition as old as Mesopotamia." },
  { id: "mandi", name: "Mandi", place: "Hadhramaut, Yemen", country: "Yemen", lat: 16.05, lon: 49.0, fact: "From Yemen's Hadhramaut valley: meat and rice cooked in a sealed underground tandoor so the smoke perfumes every grain." },
];
